# Generated by Django 4.2.6 on 2023-10-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_is_sold_alter_product_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Price'),
        ),
    ]
